###
# This is a comment
GET https://jsonplaceholder.typicode.com/posts/1

###
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
	"key": "value"
}

###
# @no-log
# @timeout 3
POST http://192.168.103.195:3300/users
Content-Type: application/json

{
	"name": "toto",
	"age": 30
}

###
GET http://localhost:3000

###
# @no-log
#@html
GET http://google.com
